flowchart LR

  %% === Node Definitions ===

  %% ANTs / Intermodal Registration
  antsIntermodalityIntrasubject_sh["antsIntermodalityIntrasubject.sh"]

  %% === Edges ===

  %% ANTs / Intermodal Registration (intra-subsection)
  antsIntermodalityIntrasubject_sh --> antsIntermodalityIntrasubject_sh
