flowchart LR

  %% === Node Definitions ===

  %% FreeSurfer / PET Processing
  mri_gtmpvc["mri_gtmpvc"]

  %% === Edges ===

  %% FreeSurfer / PET Processing (intra-subsection)
  mri_gtmpvc --> mri_gtmpvc
